name: Upload

on:
  push:
    branches: [ master ]

jobs:
  upload:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install pod
      working-directory: "MCSL Mobile"
      run: pod install
    - name: Upload build
      working-directory: "MCSL Mobile"
      run: fastlane beta
      env: 
        FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
        FASTLANE_SESSION: ${{ secrets.FASTLANE_SESSION }}
        MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
        MATCH_GIT_PRIVATE_KEY: ${{ secrets.MATCH_GIT_PRIVATE_KEY }}
        FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{ secrets.FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD }} 
